name: Docker Image CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git Semantic Version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          major_pattern: 'fix:'
          minor_pattern: 'feat:'
          format: '${major}.${minor}.${patch}-prerelease${increment}'
        id: version

      - name: Docker login
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker immage
        run: |
          docker build . -t victor828/docker-graphql:1.0.2

      - name: Push Docker immage
        run: |
          docker push victor828/docker-graphql:1.0.2 
          docker push victor828/docker-graphql
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
